### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by grahamperrin** [jacobb84/fact-layer#5]
I'm lucky to have version `1.8.0.0` (installed in July 2021), is there any plan to reintroduce the extension to AMO? 

<https://addons.mozilla.org/addon/fact-layer/> is no longer available :-(

**Comment by jacobb84** [comment]
Hi Graham, yes I'm looking into getting it back up. It was removed by Mozilla due to "creating DOM nodes from HTML strings containing potentially unsanitized data, by assigning to innerHTML, jQuery.html, or through similar means." The data in question is coming from the fact layer json file so I don't really agree there's a security issue, but seems easier to just change the approach then to fight it :)

**Comment by jacobb84** [comment]
Just an update on this, I have an updated version of the plugin awaiting review at Mozilla. Hopefully they'll approve it.

**Comment by jacobb84** [comment]
Looks like they approved it!
